# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project krnl_read
set_top krnl_read
add_files "/home/yanghui/Desktop/myProject/multiple_krnl/krnl_vadd.cl"
open_solution solution_OCL_REGION_0
set_part xc7vx690tffg1157-2
create_clock -period 200MHz -name default
set_clock_uncertainty 1.350000
config_rtl -register_reset
config_interface -m_axi_addr64
config_schedule -relax_ii_for_timing
config_compile -pipeline_loops 64
config_compile -name_max_length 256
csynth_design -skip_cdt
export_design -format ipxact -kernel_drc -sdaccel
close_project
puts "Vivado HLS completed successfully"
exit
