// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XKRNL_WRITE_H
#define XKRNL_WRITE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xkrnl_write_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XKrnl_write_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XKrnl_write;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XKrnl_write_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XKrnl_write_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XKrnl_write_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XKrnl_write_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XKrnl_write_Initialize(XKrnl_write *InstancePtr, u16 DeviceId);
XKrnl_write_Config* XKrnl_write_LookupConfig(u16 DeviceId);
int XKrnl_write_CfgInitialize(XKrnl_write *InstancePtr, XKrnl_write_Config *ConfigPtr);
#else
int XKrnl_write_Initialize(XKrnl_write *InstancePtr, const char* InstanceName);
int XKrnl_write_Release(XKrnl_write *InstancePtr);
#endif

void XKrnl_write_Start(XKrnl_write *InstancePtr);
u32 XKrnl_write_IsDone(XKrnl_write *InstancePtr);
u32 XKrnl_write_IsIdle(XKrnl_write *InstancePtr);
u32 XKrnl_write_IsReady(XKrnl_write *InstancePtr);
void XKrnl_write_EnableAutoRestart(XKrnl_write *InstancePtr);
void XKrnl_write_DisableAutoRestart(XKrnl_write *InstancePtr);

void XKrnl_write_Set_c(XKrnl_write *InstancePtr, u64 Data);
u64 XKrnl_write_Get_c(XKrnl_write *InstancePtr);
void XKrnl_write_Set_n_elements(XKrnl_write *InstancePtr, u32 Data);
u32 XKrnl_write_Get_n_elements(XKrnl_write *InstancePtr);
void XKrnl_write_Set_p_xcl_gv_pipe_c(XKrnl_write *InstancePtr, u64 Data);
u64 XKrnl_write_Get_p_xcl_gv_pipe_c(XKrnl_write *InstancePtr);

void XKrnl_write_InterruptGlobalEnable(XKrnl_write *InstancePtr);
void XKrnl_write_InterruptGlobalDisable(XKrnl_write *InstancePtr);
void XKrnl_write_InterruptEnable(XKrnl_write *InstancePtr, u32 Mask);
void XKrnl_write_InterruptDisable(XKrnl_write *InstancePtr, u32 Mask);
void XKrnl_write_InterruptClear(XKrnl_write *InstancePtr, u32 Mask);
u32 XKrnl_write_InterruptGetEnabled(XKrnl_write *InstancePtr);
u32 XKrnl_write_InterruptGetStatus(XKrnl_write *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
