// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XKRNL_ADDER_H
#define XKRNL_ADDER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xkrnl_adder_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XKrnl_adder_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XKrnl_adder;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XKrnl_adder_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XKrnl_adder_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XKrnl_adder_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XKrnl_adder_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XKrnl_adder_Initialize(XKrnl_adder *InstancePtr, u16 DeviceId);
XKrnl_adder_Config* XKrnl_adder_LookupConfig(u16 DeviceId);
int XKrnl_adder_CfgInitialize(XKrnl_adder *InstancePtr, XKrnl_adder_Config *ConfigPtr);
#else
int XKrnl_adder_Initialize(XKrnl_adder *InstancePtr, const char* InstanceName);
int XKrnl_adder_Release(XKrnl_adder *InstancePtr);
#endif

void XKrnl_adder_Start(XKrnl_adder *InstancePtr);
u32 XKrnl_adder_IsDone(XKrnl_adder *InstancePtr);
u32 XKrnl_adder_IsIdle(XKrnl_adder *InstancePtr);
u32 XKrnl_adder_IsReady(XKrnl_adder *InstancePtr);
void XKrnl_adder_EnableAutoRestart(XKrnl_adder *InstancePtr);
void XKrnl_adder_DisableAutoRestart(XKrnl_adder *InstancePtr);

void XKrnl_adder_Set_n_elements(XKrnl_adder *InstancePtr, u32 Data);
u32 XKrnl_adder_Get_n_elements(XKrnl_adder *InstancePtr);
void XKrnl_adder_Set_p_xcl_gv_pipe_a(XKrnl_adder *InstancePtr, u64 Data);
u64 XKrnl_adder_Get_p_xcl_gv_pipe_a(XKrnl_adder *InstancePtr);
void XKrnl_adder_Set_p_xcl_gv_pipe_b(XKrnl_adder *InstancePtr, u64 Data);
u64 XKrnl_adder_Get_p_xcl_gv_pipe_b(XKrnl_adder *InstancePtr);
void XKrnl_adder_Set_p_xcl_gv_pipe_c(XKrnl_adder *InstancePtr, u64 Data);
u64 XKrnl_adder_Get_p_xcl_gv_pipe_c(XKrnl_adder *InstancePtr);

void XKrnl_adder_InterruptGlobalEnable(XKrnl_adder *InstancePtr);
void XKrnl_adder_InterruptGlobalDisable(XKrnl_adder *InstancePtr);
void XKrnl_adder_InterruptEnable(XKrnl_adder *InstancePtr, u32 Mask);
void XKrnl_adder_InterruptDisable(XKrnl_adder *InstancePtr, u32 Mask);
void XKrnl_adder_InterruptClear(XKrnl_adder *InstancePtr, u32 Mask);
u32 XKrnl_adder_InterruptGetEnabled(XKrnl_adder *InstancePtr);
u32 XKrnl_adder_InterruptGetStatus(XKrnl_adder *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
