// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xkrnl_read.h"

extern XKrnl_read_Config XKrnl_read_ConfigTable[];

XKrnl_read_Config *XKrnl_read_LookupConfig(u16 DeviceId) {
	XKrnl_read_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XKRNL_READ_NUM_INSTANCES; Index++) {
		if (XKrnl_read_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XKrnl_read_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XKrnl_read_Initialize(XKrnl_read *InstancePtr, u16 DeviceId) {
	XKrnl_read_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XKrnl_read_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XKrnl_read_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

