// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XKRNL_READ_H
#define XKRNL_READ_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xkrnl_read_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XKrnl_read_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XKrnl_read;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XKrnl_read_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XKrnl_read_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XKrnl_read_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XKrnl_read_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XKrnl_read_Initialize(XKrnl_read *InstancePtr, u16 DeviceId);
XKrnl_read_Config* XKrnl_read_LookupConfig(u16 DeviceId);
int XKrnl_read_CfgInitialize(XKrnl_read *InstancePtr, XKrnl_read_Config *ConfigPtr);
#else
int XKrnl_read_Initialize(XKrnl_read *InstancePtr, const char* InstanceName);
int XKrnl_read_Release(XKrnl_read *InstancePtr);
#endif

void XKrnl_read_Start(XKrnl_read *InstancePtr);
u32 XKrnl_read_IsDone(XKrnl_read *InstancePtr);
u32 XKrnl_read_IsIdle(XKrnl_read *InstancePtr);
u32 XKrnl_read_IsReady(XKrnl_read *InstancePtr);
void XKrnl_read_EnableAutoRestart(XKrnl_read *InstancePtr);
void XKrnl_read_DisableAutoRestart(XKrnl_read *InstancePtr);

void XKrnl_read_Set_a(XKrnl_read *InstancePtr, u64 Data);
u64 XKrnl_read_Get_a(XKrnl_read *InstancePtr);
void XKrnl_read_Set_b(XKrnl_read *InstancePtr, u64 Data);
u64 XKrnl_read_Get_b(XKrnl_read *InstancePtr);
void XKrnl_read_Set_n_elements(XKrnl_read *InstancePtr, u32 Data);
u32 XKrnl_read_Get_n_elements(XKrnl_read *InstancePtr);
void XKrnl_read_Set_p_xcl_gv_pipe_a(XKrnl_read *InstancePtr, u64 Data);
u64 XKrnl_read_Get_p_xcl_gv_pipe_a(XKrnl_read *InstancePtr);
void XKrnl_read_Set_p_xcl_gv_pipe_b(XKrnl_read *InstancePtr, u64 Data);
u64 XKrnl_read_Get_p_xcl_gv_pipe_b(XKrnl_read *InstancePtr);

void XKrnl_read_InterruptGlobalEnable(XKrnl_read *InstancePtr);
void XKrnl_read_InterruptGlobalDisable(XKrnl_read *InstancePtr);
void XKrnl_read_InterruptEnable(XKrnl_read *InstancePtr, u32 Mask);
void XKrnl_read_InterruptDisable(XKrnl_read *InstancePtr, u32 Mask);
void XKrnl_read_InterruptClear(XKrnl_read *InstancePtr, u32 Mask);
u32 XKrnl_read_InterruptGetEnabled(XKrnl_read *InstancePtr);
u32 XKrnl_read_InterruptGetStatus(XKrnl_read *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
