// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of a
//        bit 31~0 - a[31:0] (Read/Write)
// 0x14 : Data signal of a
//        bit 31~0 - a[63:32] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of b
//        bit 31~0 - b[31:0] (Read/Write)
// 0x20 : Data signal of b
//        bit 31~0 - b[63:32] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of n_elements
//        bit 31~0 - n_elements[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of p_xcl_gv_pipe_a
//        bit 31~0 - p_xcl_gv_pipe_a[31:0] (Read/Write)
// 0x34 : Data signal of p_xcl_gv_pipe_a
//        bit 31~0 - p_xcl_gv_pipe_a[63:32] (Read/Write)
// 0x38 : reserved
// 0x3c : Data signal of p_xcl_gv_pipe_b
//        bit 31~0 - p_xcl_gv_pipe_b[31:0] (Read/Write)
// 0x40 : Data signal of p_xcl_gv_pipe_b
//        bit 31~0 - p_xcl_gv_pipe_b[63:32] (Read/Write)
// 0x44 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XKRNL_READ_CONTROL_ADDR_AP_CTRL              0x00
#define XKRNL_READ_CONTROL_ADDR_GIE                  0x04
#define XKRNL_READ_CONTROL_ADDR_IER                  0x08
#define XKRNL_READ_CONTROL_ADDR_ISR                  0x0c
#define XKRNL_READ_CONTROL_ADDR_A_DATA               0x10
#define XKRNL_READ_CONTROL_BITS_A_DATA               64
#define XKRNL_READ_CONTROL_ADDR_B_DATA               0x1c
#define XKRNL_READ_CONTROL_BITS_B_DATA               64
#define XKRNL_READ_CONTROL_ADDR_N_ELEMENTS_DATA      0x28
#define XKRNL_READ_CONTROL_BITS_N_ELEMENTS_DATA      32
#define XKRNL_READ_CONTROL_ADDR_P_XCL_GV_PIPE_A_DATA 0x30
#define XKRNL_READ_CONTROL_BITS_P_XCL_GV_PIPE_A_DATA 64
#define XKRNL_READ_CONTROL_ADDR_P_XCL_GV_PIPE_B_DATA 0x3c
#define XKRNL_READ_CONTROL_BITS_P_XCL_GV_PIPE_B_DATA 64

