// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xkrnl_adder.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XKrnl_adder_CfgInitialize(XKrnl_adder *InstancePtr, XKrnl_adder_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XKrnl_adder_Start(XKrnl_adder *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_AP_CTRL) & 0x80;
    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XKrnl_adder_IsDone(XKrnl_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XKrnl_adder_IsIdle(XKrnl_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XKrnl_adder_IsReady(XKrnl_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XKrnl_adder_EnableAutoRestart(XKrnl_adder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XKrnl_adder_DisableAutoRestart(XKrnl_adder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_AP_CTRL, 0);
}

void XKrnl_adder_Set_n_elements(XKrnl_adder *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_N_ELEMENTS_DATA, Data);
}

u32 XKrnl_adder_Get_n_elements(XKrnl_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_N_ELEMENTS_DATA);
    return Data;
}

void XKrnl_adder_Set_p_xcl_gv_pipe_a(XKrnl_adder *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_A_DATA, (u32)(Data));
    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_A_DATA + 4, (u32)(Data >> 32));
}

u64 XKrnl_adder_Get_p_xcl_gv_pipe_a(XKrnl_adder *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_A_DATA);
    Data += (u64)XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_A_DATA + 4) << 32;
    return Data;
}

void XKrnl_adder_Set_p_xcl_gv_pipe_b(XKrnl_adder *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_B_DATA, (u32)(Data));
    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_B_DATA + 4, (u32)(Data >> 32));
}

u64 XKrnl_adder_Get_p_xcl_gv_pipe_b(XKrnl_adder *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_B_DATA);
    Data += (u64)XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_B_DATA + 4) << 32;
    return Data;
}

void XKrnl_adder_Set_p_xcl_gv_pipe_c(XKrnl_adder *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_C_DATA, (u32)(Data));
    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_C_DATA + 4, (u32)(Data >> 32));
}

u64 XKrnl_adder_Get_p_xcl_gv_pipe_c(XKrnl_adder *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_C_DATA);
    Data += (u64)XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_P_XCL_GV_PIPE_C_DATA + 4) << 32;
    return Data;
}

void XKrnl_adder_InterruptGlobalEnable(XKrnl_adder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_GIE, 1);
}

void XKrnl_adder_InterruptGlobalDisable(XKrnl_adder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_GIE, 0);
}

void XKrnl_adder_InterruptEnable(XKrnl_adder *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_IER);
    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_IER, Register | Mask);
}

void XKrnl_adder_InterruptDisable(XKrnl_adder *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_IER);
    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_IER, Register & (~Mask));
}

void XKrnl_adder_InterruptClear(XKrnl_adder *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_adder_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_ISR, Mask);
}

u32 XKrnl_adder_InterruptGetEnabled(XKrnl_adder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_IER);
}

u32 XKrnl_adder_InterruptGetStatus(XKrnl_adder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XKrnl_adder_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_ADDER_CONTROL_ADDR_ISR);
}

