// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xkrnl_write.h"

extern XKrnl_write_Config XKrnl_write_ConfigTable[];

XKrnl_write_Config *XKrnl_write_LookupConfig(u16 DeviceId) {
	XKrnl_write_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XKRNL_WRITE_NUM_INSTANCES; Index++) {
		if (XKrnl_write_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XKrnl_write_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XKrnl_write_Initialize(XKrnl_write *InstancePtr, u16 DeviceId) {
	XKrnl_write_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XKrnl_write_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XKrnl_write_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

