// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xkrnl_write.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XKrnl_write_CfgInitialize(XKrnl_write *InstancePtr, XKrnl_write_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XKrnl_write_Start(XKrnl_write *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_AP_CTRL) & 0x80;
    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XKrnl_write_IsDone(XKrnl_write *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XKrnl_write_IsIdle(XKrnl_write *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XKrnl_write_IsReady(XKrnl_write *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XKrnl_write_EnableAutoRestart(XKrnl_write *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XKrnl_write_DisableAutoRestart(XKrnl_write *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_AP_CTRL, 0);
}

void XKrnl_write_Set_c(XKrnl_write *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_C_DATA, (u32)(Data));
    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_C_DATA + 4, (u32)(Data >> 32));
}

u64 XKrnl_write_Get_c(XKrnl_write *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_C_DATA);
    Data += (u64)XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_C_DATA + 4) << 32;
    return Data;
}

void XKrnl_write_Set_n_elements(XKrnl_write *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_N_ELEMENTS_DATA, Data);
}

u32 XKrnl_write_Get_n_elements(XKrnl_write *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_N_ELEMENTS_DATA);
    return Data;
}

void XKrnl_write_Set_p_xcl_gv_pipe_c(XKrnl_write *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_P_XCL_GV_PIPE_C_DATA, (u32)(Data));
    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_P_XCL_GV_PIPE_C_DATA + 4, (u32)(Data >> 32));
}

u64 XKrnl_write_Get_p_xcl_gv_pipe_c(XKrnl_write *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_P_XCL_GV_PIPE_C_DATA);
    Data += (u64)XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_P_XCL_GV_PIPE_C_DATA + 4) << 32;
    return Data;
}

void XKrnl_write_InterruptGlobalEnable(XKrnl_write *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_GIE, 1);
}

void XKrnl_write_InterruptGlobalDisable(XKrnl_write *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_GIE, 0);
}

void XKrnl_write_InterruptEnable(XKrnl_write *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_IER);
    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_IER, Register | Mask);
}

void XKrnl_write_InterruptDisable(XKrnl_write *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_IER);
    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_IER, Register & (~Mask));
}

void XKrnl_write_InterruptClear(XKrnl_write *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_write_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_ISR, Mask);
}

u32 XKrnl_write_InterruptGetEnabled(XKrnl_write *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_IER);
}

u32 XKrnl_write_InterruptGetStatus(XKrnl_write *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XKrnl_write_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_WRITE_CONTROL_ADDR_ISR);
}

